server:
  port: 8080

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  type-aliases-package: com.abing.blog.entity
  configuration:
    map-underscore-to-camel-case: true

spring:
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

  thymeleaf:
    cache: false

  datasource:
    username: hotel_face
    password: hotel_face_20200120
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.36.42.4:3306/hotel?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource

  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

  profiles:
    active: dev

logging:
  config: classpath:logback-spring.xml